### ISSUE TITLE
gazebo_samplerobot_no_controllers.launchが起動できない

### ISSUE THREAD

**Issue by ptwork13** [agent-system/homework2015#29]
Ubuntu14.04でgazebo_samplerobot_no_controllers.launchを行った際
下記のエラーが出て起動できませんでした。
ファイル自体は存在しているようですが、なにか解決法をご教示願えますでしょうか。

[gazebo_samplerobot_no_controllers.launch] is neither a launch file in package [hrpsys_gazebo_tutorials] nor is [hrpsys_gazebo_tutorials] a launch file name
The traceback for the exception was written to the log file

**Comment by furushchev** [comment]
`roscd hrpsys_gazebo_tutorials`としてみてhrpsys_gazebo_tutorialsのディレクトリに移動するでしょうか？
もししなければ

```
roscd
catkin build hrpsys_gazebo_tutorials
source setup.bash
```

としてもう一度試してみてください。
