### ISSUE TITLE
catkin build が失敗する

### ISSUE THREAD

**Issue by phenan** [agent-system/homework2015#9]
Ubuntu 14.04.2 LTS で catkin build homework20150422 に失敗します。
エラーメッセージから判断すると、cv_camera 関係の問題のようです。
rosdep check cv_camera を実行してみたところ、Missing resource cv_camera となりました。

**Comment by henoc** [comment]
同じです。

**Comment by phenan** [comment]
既出でしたね。気付きませんでした。
